---
podman_user: "sho"
podman_user_home: "/home/sho"

rclone_gdrive_token: "{{ vault_rclone_gdrive_token }}"

minecraft_ram_limit: "4G"
playit_secret_key: "{{ vault_playit_secret_key }}"

cloudflare_token: "{{ vault_cloudflared_token }}"
